language: php

matrix:
  include:
    - php: 7.1
      env:
        - PHPUNIT_VERSION=7.*
    - php: 7.2
      env:
        - PHPUNIT_VERSION=7.*
    - php: 7.2
      env:
        - PHPUNIT_VERSION=8.*
    - php: 7.3
      env:
        - PHPUNIT_VERSION=7.*
    - php: 7.3
      env:
        - PHPUNIT_VERSION=8.*

install:
  - composer require phpunit/phpunit:$PHPUNIT_VERSION;
